{
  "bugzilla": {
    "description": "containers/aardvark-dns: TCP Query Handling Flaw in Aardvark-dns Leading to Denial of Service",
    "id": "2309683",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2309683"
  },
  "csaw": false,
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "cwe": "CWE-400",
  "details": [
    "No description is available for this CVE."
  ],
  "name": "CVE-2024-8418",
  "package_state": [
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "fix_state": "Under investigation",
      "package_name": "container-tools:rhel8/aardvark-dns",
      "product_name": "Red Hat Enterprise Linux 8"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "fix_state": "Under investigation",
      "package_name": "container-tools:rhel8/containers-common",
      "product_name": "Red Hat Enterprise Linux 8"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:9",
      "fix_state": "Under investigation",
      "package_name": "aardvark-dns",
      "product_name": "Red Hat Enterprise Linux 9"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:9",
      "fix_state": "Under investigation",
      "package_name": "containers-common",
      "product_name": "Red Hat Enterprise Linux 9"
    },
    {
      "cpe": "cpe:/a:redhat:openshift:4",
      "fix_state": "Under investigation",
      "package_name": "rhcos",
      "product_name": "Red Hat OpenShift Container Platform 4"
    }
  ],
  "public_date": "2024-09-04T10:00:00Z",
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-8418\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-8418\nhttps://github.com/containers/aardvark-dns/issues/500\nhttps://github.com/containers/aardvark-dns/pull/503"
  ],
  "threat_severity": "Moderate"
}